---
grafana_security:
  admin_user: admin
  admin_password: changeme
#  admin_password: "{{ vault_grafana_password }}"

grafana_auth:
  anonymous:
    org_name: "Main Org."
    org_role: Viewer

grafana_datasources:
- name: "Prometheus"
  type: "prometheus"
  access: "proxy"
  url: "http://{{ ansible_host }}:9090"
  isDefault: true

grafana_dashboards:
  # Node exporter full
  - dashboard_id: '1860'
    revision_id: '21'
    datasource: '{{ grafana_datasources.0.name }}'
  # Prometheus overview
  - dashboard_id: '3662'
    revision_id: '2'
    datasource: '{{ grafana_datasources.0.name }}'
  # Docker
#  - dashboard_id: '4271'
#    revision_id: '4'
#    datasource: '{{ grafana_datasources.0.name }}'
#  Slurm
#  - dashboard_id: '4323'
#    revision_id: '2'
#    datasource: '{{ grafana_datasources.0.name }}'
  # openHPC dashboard
  - dashboard_id: '10809'
    revision_id: '2'
    datasource: '{{ grafana_datasources.0.name }}'
